version: "2"

services:
    mariadb:
        image: wodby/mariadb:$MARIADB_TAG
        container_name: "${PROJECT_NAME}_mariadb"
        stop_grace_period: 30s
        environment:
            MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
            MYSQL_DATABASE: $DB_NAME
            MYSQL_USER: $DB_USER
            MYSQL_PASSWORD: $DB_PASSWORD

    php:
        image: wodby/php:$PHP_TAG
        container_name: "${PROJECT_NAME}_php"
        environment:
            PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
            PHP_XDEBUG: 1
            PHP_XDEBUG_DEFAULT_ENABLE: 1
            PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
            PHP_IDE_CONFIG: serverName=default
            PHP_XDEBUG_REMOTE_HOST: 172.17.0.1 # Linux
        volumes:
            - ./www:/var/www/html

    nginx:
        image: wodby/php-nginx:$NGINX_TAG
        container_name: "${PROJECT_NAME}_nginx"
        depends_on:
            - php
        environment:
            NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
            NGINX_ERROR_LOG_LEVEL: debug
            NGINX_BACKEND_HOST: php
            NGINX_SERVER_ROOT: /var/www/html/public
        volumes:
            - ./symfony-nginx-conf.sh:/docker-entrypoint-init.d/20-symfony-nginx-conf.sh
            - ./www:/var/www/html
        labels:
            - 'traefik.backend=nginx'
            - 'traefik.port=80'
            - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'

    mailhog:
        image: mailhog/mailhog
        container_name: "${PROJECT_NAME}_mailhog"
        labels:
            - 'traefik.backend=mailhog'
            - 'traefik.port=8025'
            - 'traefik.frontend.rule=Host:mailhog.${PROJECT_BASE_URL}'

    adminer:
        container_name: "${PROJECT_NAME}_adminer"
        image: wodby/adminer:$ADMINER_TAG
        environment:
            ADMINER_SALT: adminer-salt
        labels:
            - 'traefik.backend=adminer'
            - 'traefik.port=9000'
            - 'traefik.frontend.rule=Host:adminer.${PROJECT_BASE_URL}'

    traefik:
        image: traefik
        container_name: "${PROJECT_NAME}_traefik"
        command: -c /dev/null --web --docker --logLevel=INFO
        ports:
            - '8091:80'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
